/* This file was generated by mib2c and is intended for use as a mib module
  for the ucd-snmp snmpd agent. */


#ifndef _MIBGROUP_RMON_H
#define _MIBGROUP_RMON_H


/* we may use header_generic and header_simple_table from the util_funcs module */


config_require(util_funcs)


/* function prototypes */


void   init_rmon(void);
FindVarMethod var_rmon;
FindVarMethod var_etherStatsTable;

FindVarMethod var_historyControlTable;

FindVarMethod var_etherHistoryTable;

FindVarMethod var_alarmTable;

FindVarMethod var_hostControlTable;

FindVarMethod var_hostTable;

FindVarMethod var_hostTimeTable;

FindVarMethod var_hostTopNControlTable;

FindVarMethod var_hostTopNTable;

FindVarMethod var_matrixControlTable;

FindVarMethod var_matrixSDTable;

FindVarMethod var_matrixDSTable;

FindVarMethod var_filterTable;

FindVarMethod var_channelTable;

FindVarMethod var_bufferControlTable;

FindVarMethod var_captureBufferTable;

FindVarMethod var_eventTable;

FindVarMethod var_logTable;


WriteMethod write_etherStatsDataSource;
WriteMethod write_etherStatsOwner;
WriteMethod write_etherStatsStatus;
WriteMethod write_historyControlDataSource;
WriteMethod write_historyControlBucketsRequested;
WriteMethod write_historyControlInterval;
WriteMethod write_historyControlOwner;
WriteMethod write_historyControlStatus;
WriteMethod write_alarmInterval;
WriteMethod write_alarmVariable;
WriteMethod write_alarmSampleType;
WriteMethod write_alarmStartupAlarm;
WriteMethod write_alarmRisingThreshold;
WriteMethod write_alarmFallingThreshold;
WriteMethod write_alarmRisingEventIndex;
WriteMethod write_alarmFallingEventIndex;
WriteMethod write_alarmOwner;
WriteMethod write_alarmStatus;
WriteMethod write_hostControlDataSource;
WriteMethod write_hostControlOwner;
WriteMethod write_hostControlStatus;
WriteMethod write_hostTopNHostIndex;
WriteMethod write_hostTopNRateBase;
WriteMethod write_hostTopNTimeRemaining;
WriteMethod write_hostTopNRequestedSize;
WriteMethod write_hostTopNOwner;
WriteMethod write_hostTopNStatus;
WriteMethod write_matrixControlDataSource;
WriteMethod write_matrixControlOwner;
WriteMethod write_matrixControlStatus;
WriteMethod write_filterChannelIndex;
WriteMethod write_filterPktDataOffset;
WriteMethod write_filterPktData;
WriteMethod write_filterPktDataMask;
WriteMethod write_filterPktDataNotMask;
WriteMethod write_filterPktStatus;
WriteMethod write_filterPktStatusMask;
WriteMethod write_filterPktStatusNotMask;
WriteMethod write_filterOwner;
WriteMethod write_filterStatus;
WriteMethod write_channelIfIndex;
WriteMethod write_channelAcceptType;
WriteMethod write_channelDataControl;
WriteMethod write_channelTurnOnEventIndex;
WriteMethod write_channelTurnOffEventIndex;
WriteMethod write_channelEventIndex;
WriteMethod write_channelEventStatus;
WriteMethod write_channelDescription;
WriteMethod write_channelOwner;
WriteMethod write_channelStatus;
WriteMethod write_bufferControlChannelIndex;
WriteMethod write_bufferControlFullAction;
WriteMethod write_bufferControlCaptureSliceSize;
WriteMethod write_bufferControlDownloadSliceSize;
WriteMethod write_bufferControlDownloadOffset;
WriteMethod write_bufferControlMaxOctetsRequested;
WriteMethod write_bufferControlOwner;
WriteMethod write_bufferControlStatus;
WriteMethod write_eventDescription;
WriteMethod write_eventType;
WriteMethod write_eventCommunity;
WriteMethod write_eventOwner;
WriteMethod write_eventStatus;



#endif /* _MIBGROUP_RMON_H */
