#!/bin/sh

echo "        Setting SuSE specific flag values"
LDFLAGS="${LDFLAGS} -L/usr/X11R6/lib"

if ! test -f /usr/X11R6/lib/libXpm.so; then
    echo
    echo "*******************************************************************"
    echo "*"
    echo "*             -lXpm not found, because the libXpm.so file does not"
    echo "*             exist."
    echo "*"
    echo "*>>> Continuing, but subsequent make may fail"
    echo "*"
    echo "*???     1. As root, create the link:"
    echo "*???        ln -s /usr/X11R6/lib/libXpm.so.4 /usr/X11R6/lib/libXpm.so"
    echo "*"
    echo "*******************************************************************"
    echo
    HAS_WARNING="yes"
fi
if ! test -f /usr/X11R6/lib/libX11.so; then
    echo
    echo "*******************************************************************"
    echo "*"
    echo "*             -lX11 not found, because the libX11.so file does not"
    echo "*             exist."
    echo "*"
    echo "*>>> Continuing, but subsequent make may fail"
    echo "*"
    echo "*???     1. As root, create the link:"
    echo "*???        ln -s /usr/X11R6/lib/libX11.so.6.2 /usr/X11R6/lib/libX11.so"
    echo "*"
    echo "*******************************************************************"
    echo
    HAS_WARNING="yes"
fi
