#!/bin/sh

echo "        Setting SuSE specific flag values"
LDFLAGS="${LDFLAGS} -L/usr/X11R6/lib -L/usr/lib64"

if ! test -f /usr/X11R6/lib/libXpm.so -o -f /usr/lib64/libXpm.so; then
    echo
    echo "*******************************************************************"
    echo "*"
    echo "*             -lXpm not found, because the libXpm.so file does not"
    echo "*             exist."
    echo "*"
    echo "*>>> Continuing, but subsequent make may fail"
    echo "*"
    echo "*???     1. Install the X development packages:"
    echo "*???        yast -i xorg-x11-devel"
    echo "*"
    echo "*******************************************************************"
    echo
    HAS_WARNING="yes"
fi
if ! test -f /usr/X11R6/lib/libX11.so -o -f /usr/lib64/libX11.so; then
    echo
    echo "*******************************************************************"
    echo "*"
    echo "*             -lX11 not found, because the libX11.so file does not"
    echo "*             exist."
    echo "*"
    echo "*>>> Continuing, but subsequent make may fail"
    echo "*"
    echo "*???     1. Install the X development packages:"
    echo "*???        yast -i xorg-x11-devel"
    echo "*"
    echo "*******************************************************************"
    echo
    HAS_WARNING="yes"
fi
