#!/bin/sh

echo "        Setting RedHat 9 specific flag values"

# If we have krb5.h and openssl was compiled with it, we need the -I setting
# since there's no way to easily test the latter and no harm from an extra -I,
# just do it...
if test -d /usr/kerberos/include &&
   test -f /usr/kerberos/include/krb5.h; then
    CPPFLAGS="-I/usr/kerberos/include/ ${CPPFLAGS}"
fi

echo
echo "*******************************************************************"
echo "*"
echo "* WARNING:    Under RedHat Linux 9.0 (and 8.0 with updated glibc"
echo "*             rpms), there have been reported problems due to"
echo "*             the inclusion of NPTL (new POSIX Thread Library)"
echo "*             including mysterious crashes, broken debug, etc."
echo "*"
echo "*>>> Continuing, but well, y'all been warned..."
echo "*"
echo "*???     1. ntop 2.2.3 (cvs versions after xx-Jul-2003) have all"
echo "*???        the known fixes."
echo "*???  or 2. Before both ./configure AND make, set the following flag:"
echo "*???        export LD_ASSUME_KERNEL=2.4.1"
echo "*???        (This forces the use of the old linuxthreads library)"
echo "*"
echo "*******************************************************************"
echo
HAS_WARNING="yes"
