#!/bin/sh

# Clone from RedHat 9 - assuming Fedora is approx RedHat 10...

echo "        Setting Fedora specific flag values"

# If we have krb5.h and openssl was compiled with it, we need the -I setting
# since there's no way to easily test the latter and no harm from an extra -I,
# just do it...
if test -d /usr/kerberos/include &&
   test -f /usr/kerberos/include/krb5.h; then
    CPPFLAGS="-I/usr/kerberos/include/ ${CPPFLAGS}"
fi

# XML Dump plugin stuff...
#  Note - this assumes you've installed the RH rpms:
#         glib, glib-devel, libxml2, libxml2-devel
#         and the gdome2 and gdome2-devel rpms from http://gdome2.cs.unibo.it/
if pkg-config --exists --print-errors glib-2.0; then
  LIBS="${LIBS} "`pkg-config --libs glib-2.0`
  CPPFLAGS="${CPPFLAGS} "`pkg-config --cflags-only-I glib-2.0`
else
  if test -f /usr/lib/libglib.so; then
    LIBS="${LIBS} -lglib"
  fi
  if test -d /usr/include/glib-1.2; then
    CPPFLAGS="${CPPFLAGS} -I/usr/include/glib-1.2"
  fi
  if test -d /usr/lib/glib-1.2/include; then
    CPPFLAGS="${CPPFLAGS} -I/usr/lib/glib-1.2/include"
  fi
  if test -d /usr/lib/glib/include; then
    CPPFLAGS="${CPPFLAGS} -I/usr/lib/glib/include"
  fi
fi
if pkg-config --exists --print-errors gdome2; then
  LIBS="${LIBS} "`pkg-config --libs gdome2`
  CPPFLAGS="${CPPFLAGS} "`pkg-config --cflags-only-I gdome2`
else
  if test -d /usr/include/libgdome; then
    CPPFLAGS="${CPPFLAGS} -I/usr/include/libgdome"
  fi
fi
