#/* #undef CFG_BIG_ENDIAN */
#
#/* Configuration file directory */
##define CFG_CONFIGFILE_DIR "/usr/share/ntop"
#
BEGIN {
    print "/*                                                       B E G I N"
    print " *"
    print " * Autogenerated from config.h and inserted into webInterface.c "
    print " *      " strftime()
    print " *"
    print " */"
    print ""
}

{
    if ($2 == "*") {
        print "  printFeatureConfigInfo(textPrintFlag, \"" $1 "\","
        print "#ifdef " $1
        print "                         \"present\""
        print "#else"
        print "                         \"absent\""
        print "#endif"
        print "                         );"
    } else if (substr($2, 1, 1) == "\"") {
        print "  printFeatureConfigInfo(textPrintFlag, \"" $1 "\", " $1 ");"
    } else {
        print "/* Unable to autogen for " $0 " */"
    }
    print ""
}

END {
    print "/*                                                       E N D"
    print " *"
    print " * Autogenerated from config.h and inserted into webInterface.c "
    print " *"
    print " */"
    print ""
}
