<HTML>
<HEAD>
<META HTTP-EQUIV=Pragma CONTENT=no-cache>
<META HTTP-EQUIV=Cache-Control CONTENT=no-cache>
<LINK REL=stylesheet HREF=/style.css type="text/css">
</HEAD>
<BODY BACKGROUND=/white_bg.gif BGCOLOR="#FFFFFF" LINK=blue VLINK=blue>
<CENTER>
<H1><FONT FACE="Helvetica, Arial, Sans Serif">Welcome to
ntop!</FONT></H1><P>
</CENTER>
<FONT FACE=Helvetica>
<HR>
<b>ntop</b> shows the current network usage. It displays a list of
hosts that are
currently using the network and reports information concerning the IP
(Internet Protocol) traffic generated by each host. The traffic is 
sorted according to host and protocol.
<p>
<b>ntop</b>'s author strongly believes in <A
HREF=http://www.opensource.org/>
open source software</A> and encourages everyone to modify, improve
 and extend <b>ntop</b> in the interest of the whole Internet
 community according
to the enclosed licence (see COPYING).<p>Problems, bugs, questions,
desirable enhancements, source code contributions, etc., should be
sent to the <A HREF=mailto:ntop@ntop.org> mailing list</A>.
</font>
<P><HR>
</BODY>
</HTML>
